# Generated by Django 4.1.3 on 2022-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mdp',
            field=models.CharField(max_length=25, verbose_name='password'),
        ),
    ]
